<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit392b6fc69040739e00c0c5a044f9ce59
{
    public static $prefixesPsr0 = array (
        'P' => 
        array (
            'Parsedown' => 
            array (
                0 => __DIR__ . '/..' . '/erusev/parsedown',
            ),
        ),
        'M' => 
        array (
            'Monolog' => 
            array (
                0 => __DIR__ . '/..' . '/monolog/monolog/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit392b6fc69040739e00c0c5a044f9ce59::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
