<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Parsedown' => array($vendorDir . '/erusev/parsedown'),
    'Monolog' => array($vendorDir . '/monolog/monolog/src'),
);
